version: '3'
services:
 mysql:
  image: mysql
  ports:
   - 3306:3306
  restart: always
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: redhat
 adminer:
  image: adminer
  ports:
   - 8080:8080
  restart: always
  depends_on:
   - mysql
